### ISSUE TITLE
build image with docker has error

### ISSUE THREAD

**Issue by mojtaba-naserei** [elastic/curator#1597]
## To submit a bug or report an issue
when i built image with below command
docker build -t curator .

### Expected Behavior
i expected Successfully built 0bda59c3b123 , but i got error

### Actual Behavior
`running build_exe
/usr/local/lib/python3.7/site-packages/cx_Freeze/common.py:129: UserWarning: camelCase values is obsolete and will be removed in the next major version -> use the new name 'target_name'
  "camelCase values is obsolete and will be removed in the "
Traceback (most recent call last):
  File "setup.py", line 141, in <module>
    executables = [curator_exe,curator_cli_exe,repomgr_exe]
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze/dist.py", line 397, in setup
    distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze/dist.py", line 260, in run
    zipExcludePackages=self.zip_exclude_packages,
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze/freezer.py", line 88, in __init__
    self._VerifyConfiguration()
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze/freezer.py", line 551, in _VerifyConfiguration
    self.patchelf = Patchelf()
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze/patchelf.py", line 15, in __init__
    _verify_patchelf()
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze/patchelf.py", line 52, in _verify_patchelf
    raise ValueError("Cannot find required utility `patchelf` in PATH")
ValueError: Cannot find required utility `patchelf` in PATH
`

### Steps to Reproduce the Problem

  1. i added 'patchelf-wrapper' to  requirements.txt 

problem solved , please add it to requirements.txt

### Specifications

  - Version: 5.8.3
  - Platform: Ubuntu 20.04.1 LTS

**Comment by untergeek** [comment]
Thank you for the bug report, but `requirements.txt` is not where `patchelf-wrapper` belongs. It _only_ is used by `cx_Freeze` during package-building, and never by Curator itself.

I have added it to my package build (not yet committed) and to the Dockerfile (also not yet committed) where it is used by `cx_Freeze`, and it is working well.  These changes will be committed soon.

**Comment by untergeek** [comment]
Resolved in 5.8.4 release.

**Comment by foxylion** [comment]
@untergeek this is actually still present in the https://github.com/elastic/curator/releases/tag/v5.8.4 tag.
The changes released there do not contain the commit 5b29303251ca21d7f6bbd272bb78ff762402119a that has the fixes for the issue.
