### ISSUE TITLE
curator version 3.2.2: Error when trying to deleting closed indice

### ISSUE THREAD

**Issue by allenmchan** [elastic/curator#442]
I am trying to delete really old indices that have been closed for awhile. I cannot tell if this is issue with curator or elasticsearch. I see no new log entries in the master node's elasticsearch log

My command is
sudo curator --debug --logfile=/var/log/curator/delete.log delete indices --older-than 200 --time-unit days --timestring '%Y.%m.%d'

Here is the part in the curator log where the error occurs. 
https://gist.github.com/allenmchan/bfc1a98e6067619afe3b

Thanks

**Comment by untergeek** [comment]
This was addressed by version 3.2.3



—Aaron

**Comment by allenmchan** [comment]
My apologies, i didnt even realize there is a newer version. Let me test that right now.

**Comment by allenmchan** [comment]
Looks like the python error is now gone with the latest version. i still see curator can only close 4-5 indices per run. I guess i will close this and open a ticket on the elasticsearch side to troubleshoot.

**Comment by untergeek** [comment]
Have you tried increasing the --timeout value?  You should be able to go as high as 300 with the current build of Curator. 



—Aaron

**Comment by allenmchan** [comment]
You are awesome. Looks like adjusting timeout does indeed help. The longer the timeout the more i can close now. Thanks for the lightning fast response on the weekend.
